# Generated by Django 2.1.2 on 2018-10-23 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_guestemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='first_refer',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='fourth_refer',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='second_refer',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='third_refer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_refer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fourth_refer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_refer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='third_refer',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='level',
            field=models.CharField(choices=[('a_positive', 'A+'), ('g', 'Genius'), ('h', 'Hardworking'), ('b', 'Beast'), ('n', 'Ninja')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('a_positive', 'A+'), ('g', 'Genius'), ('h', 'Hardworking'), ('b', 'Beast'), ('n', 'Ninja')], default=datetime.datetime(2018, 10, 23, 15, 17, 21, 304750, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
    ]
