# Generated by Django 2.1.2 on 2018-10-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181023_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile',
            name='weekly_lead',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekly_lead',
        ),
    ]
