# Generated by Django 2.1.2 on 2018-10-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181023_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='blood',
            field=models.CharField(choices=[('a_positive', 'A+'), ('g', 'Genius'), ('h', 'Hardworking'), ('b', 'Beast'), ('n', 'Ninja')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood',
            field=models.CharField(choices=[('a_positive', 'A+'), ('g', 'Genius'), ('h', 'Hardworking'), ('b', 'Beast'), ('n', 'Ninja')], max_length=20),
        ),
    ]
