# Generated by Django 2.1.2 on 2018-10-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181025_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='first_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='second_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
